import {
    IconApple,
    IconBath,
    IconBottle,
    IconBabyCarriage,
    IconBed,
    IconBook,
    IconBrush,
    IconCategory,
    IconDeviceMobile,
    IconDog,
    IconFlower,
    IconHeartHandshake,
    IconHorseToy,
    IconJacket,
    IconMedicalCross,
    IconPill,
    IconScissors,
    IconShirt,
    IconShoe,
    IconSofa,
    IconSportBillard,
    IconStar,
    IconToolsKitchen2,
    IconTrendingUp,
    IconWash,
    IconWeight,
} from '@tabler/icons-react';

const MAP = {
    'продукты': IconApple,
    'еда': IconApple,
    'food': IconApple,
    'groceries': IconApple,
    'бакалея': IconApple,
    'косметика': IconBrush,
    'красота': IconFlower,
    'beauty': IconBrush,
    'бад': IconPill,
    'витамины': IconPill,
    'бады': IconPill,
    'здоровье': IconMedicalCross,
    'health': IconPill,
    'фарм': IconPill,
    'бытовая химия': IconWash,
    'химия': IconWash,
    'хозтовары': IconWash,
    'cleaning': IconWash,
    'уход за волосами': IconScissors,
    'волосы': IconScissors,
    'hair': IconScissors,
    'посуда': IconToolsKitchen2,
    'кухня': IconToolsKitchen2,
    'kitchen': IconToolsKitchen2,
    'одежда': IconShirt,
    'clothing': IconShirt,
    'apparel': IconShirt,
    'верхняя одежда': IconJacket,
    'куртки': IconJacket,
    'обувь': IconShoe,
    'shoes': IconShoe,
    'электроника': IconDeviceMobile,
    'гаджеты': IconDeviceMobile,
    'electronics': IconDeviceMobile,
    'мебель': IconSofa,
    'интерьер': IconSofa,
    'furniture': IconSofa,
    'уход за кожей': IconFlower,
    'уход за телом': IconFlower,
    'skincare': IconFlower,
    'детское': IconBabyCarriage,
    'дети': IconBabyCarriage,
    'baby': IconBabyCarriage,
    'игрушки': IconHorseToy,
    'toys': IconHorseToy,
    'зоотовары': IconDog,
    'питомцы': IconDog,
    'pets': IconDog,
    'спорт': IconWeight,
    'фитнес': IconWeight,
    'sports': IconWeight,
    'книги': IconBook,
    'канцелярия': IconBook,
    'гигиена': IconHeartHandshake,
    'уход': IconHeartHandshake,
    'средства личной гигиены': IconBath,
    'личная гигиена': IconBath,
    'personal hygiene': IconBath,
    'трендовые товары': IconTrendingUp,
    'тренды': IconTrendingUp,
    'trend': IconTrendingUp,
    'trending': IconTrendingUp,
    'парфюм': IconStar,
    'парфюмерия': IconStar,
    'perfume': IconStar,
    'чистящие': IconWash,
    'спортинвентарь': IconSportBillard,
    'напитки': IconBottle,
    'beverages': IconBottle,
    'постельное': IconBed,
    'постель': IconBed,
};

export function getCategoryIcon(name = '') {
    const lower = name.toLowerCase();

    if (MAP[lower]) {
        return MAP[lower];
    }

    for (const [key, Icon] of Object.entries(MAP)) {
        if (lower.includes(key) || key.includes(lower)) {
            return Icon;
        }
    }

    return IconCategory;
}
